### ISSUE TITLE
[Discussion] Naming for the `build` events

### ISSUE THREAD

**Issue by dgrcode** [moonshotcollective/scaffold-directory#134]
We currently only have one events for builds: `build.create`. That's the event recorded when someone sends a build for review by an admin.

On the challenges side we have 3 events: `challenge.submit`, `challenge.review`, and `challenge.create`.

I think for consistency with challenges we should have the following events:
 - `build.submit`: when someone submits a new build for review. That's when the build is created as draft in the database.
 - `build.create`: when the build is approved by an admin. That's when the build becomes "published" .
 - `build.rejected`: when the build is rejected by an admin. What we do with a rejected build is probably a different conversation.

I've filtered in the real db and we only have 5 submissions and all for testing, so we should be good to change the names if we want to.

Thoughts @carletex?

**Comment by carletex** [comment]
On the challenge side, it seems that we are only using `challenge.submit` and `challenge.review` at the moment.

Maybe we only need those two. And same for builds: submit and review. Review will have the status, comments, etc as the payload (we can always query by status if we want accepted / rejected challenges).

An outline of the tasks could be:
- [ ] Remove challenge.create
- [ ] Add build.submit and build.review
  - [ ] Migrate the existing `builds.create` (maybe just deleted them, since are tests)
  - [ ] Change create => submit on build /POST
  - [ ] Emit build.review on build /PATCH

WDYT @dgrcode ?

**Comment by dgrcode** [comment]
yeah I like that more. It's more consistent with the challenges. Let's go for it 👍
